### ISSUE TITLE
can we split out multiple targets post 1GC?

### ISSUE THREAD

**Issue by o-smirnov** [IanHeywood/oxkat#1]
Pretty please!

**Comment by IanHeywood** [comment]
Try this one chief:

https://github.com/IanHeywood/oxkat/blob/master/oxkat/casa_refcal_multiple_targets.py

If you put your (flagged) multisource MS file in a folder on its own, start CASA and execfile this, then hopefully it will perform the 1GC step and split out unique 1GC-calibrated target data, one Measurement Set per target.

If the scan intents are as standard then it will identify cals and targets. It should also automatically pick a reference antenna as well as identify the primary via a position match to select the right model.

Please post here if there are any issues.

Cheers.

**Comment by o-smirnov** [comment]
Cool! What would you recommend for pre-flagging?

**Comment by IanHeywood** [comment]
Try this:

https://github.com/IanHeywood/oxkat/blob/master/oxkat/casa_basic_flags.py

Which will do some very simple flagging steps on whatever MS is in the directory. Again, should just be able to run this from CASA with no other setup required. These steps are generally good enough for continuum work in my experience. I used to use the SARAO RFI mask from June of last year, but the bad regions here are the ones that the IDIA folks use in their pipeline.

I need to revisit flagging strategies generally I think, try out tricolor which Ben tells me is working very nicely, and is super fast...

**Comment by o-smirnov** [comment]
OK, some indents needed fixing, but now it's running.

Can you give me access to the repo so I can issue PRs?

**Comment by IanHeywood** [comment]
Done, I think.

Cheers.

**Comment by o-smirnov** [comment]
OK these are the fixes, does the logic look right? I assumed it was just some stray tabs: https://github.com/IanHeywood/oxkat/commit/7b2369fa9a627b260794d05c773c7ee239cad151

It's busy chugging away on my MS right now. I'll issue a PR if it succeeds.

**Comment by IanHeywood** [comment]
Yup, looks right.

Cheers.
