### ISSUE TITLE
Singularity pulls containers in .sif format (node mode)

### ISSUE THREAD

**Issue by shilparanchod** [IanHeywood/oxkat#11]
Hi Ian
When running the pull_containers.sh script, the containers are downloaded as .sif format, which are not recognised when running `$ python setups/1GC.py node`. I get the following error: "Failed to find container for casa in /users/shilpa/containers/".

**Comment by IanHeywood** [comment]
Hi @shilparanchod. Is this on the IDIA cluster? I noticed the same thing when I tried to make a script to build the containers that could be submitted as a one-off job via the slurm queue. I'm not yet sure why the worker nodes have this different behaviour.

If you can log in to a standalone node (e.g. `dipper`) then the `pull_containers.sh` script should work...

**Comment by IanHeywood** [comment]
OK it looks like it's a singularity version issue. 

On dipper:

```
$ singularity --version
2.6.1-dist
```

On a worker node:

```
$ singularity --version
singularity version 3.5.2
```

And from a quick Google search:

```
Singularity Image Format (SIF)
Singularity images use the *.sif suffix
Earlier versions use the *.simg suffix
```

The script that finds containers for you isn't wise to this yet:

https://github.com/IanHeywood/oxkat/blob/master/oxkat/generate_jobs.py#L31

**Comment by IanHeywood** [comment]
b1900647ec3ceea32d33a68a62b7dd6a1be0b8f1

**Comment by IanHeywood** [comment]
Hi Shilpa, this should be fixed now, with the script finding either sif or simg format containers.
