### ISSUE TITLE
astropy warning

### ISSUE THREAD

**Issue by rdeane** [IanHeywood/oxkat#17]
When running the setup script ```1GC_00_setup.py```, I get the following python warnings, which I'm not sure impact anything yet but posting nonetheless. It is raised on the [astropy repo here](https://github.com/astropy/astropy/issues/5726), but seems it could be related to a test script.  

> WARNING: Couldn't write lextab module 'astropy.coordinates.angle_lextab'. [Errno 30] Read-only file system: '/usr/lib/python2.7/dist-packages/astropy/coor
dinates/angle_lextab.py'
WARNING: Couldn't create 'astropy.coordinates.angle_parsetab'. [Errno 30] Read-only file system: '/usr/lib/python2.7/dist-packages/astropy/coordinates/ang
le_parsetab.py'

**Comment by IanHeywood** [comment]
Thanks @rdeane. I get the same warning when running on IDIA machines when I'm watching the terminal output. I don't know if CHPC has this issue too, as the warnings don't seem to end up in the slurm / PBS logs.

Astropy is used to calculate target-cal separations in that script which it happily does despite the warning, so I think the messages are unsightly but harmless.

I guess it's more of a container / environment config issue than an oxkat issue. If it's not doing anything destructive I'm probably never going to invest the time chasing it up, but please re-open if you find it's messing things up.

**Comment by rdeane** [comment]
yeah, totally agreed. This is more just for the record and future students searching through the issue list before asking about it.

**Comment by IanHeywood** [comment]
Tempted to re-open to this advice to remember to delete the `is:open` filter when searching issues remains visible.

**Comment by rdeane** [comment]
nah, I would just add to the README that ```is:closed``` should be searched before posting new issues and when assessing any warnings / grumbles within pipeline runs.
