### ISSUE TITLE
submit script has bash variable error

### ISSUE THREAD

**Issue by dentalfloss1** [IanHeywood/oxkat#31]
Sometime in the past month the submit script was altered to have bash variables with a period. This causes the submit script to fail because bash variables can (for the most part) only consist of letters and numbers.

**Comment by IanHeywood** [comment]
What is the name of the MS?

**Comment by dentalfloss1** [comment]
1590189641-GX339only.ms
I was looking at some peculiar WSClean behavior in a GRB dataset and I was looking to compare.

**Comment by IanHeywood** [comment]
OK this isn't a past month thing. It assumes the input MS is named as they come from the archive, so it tries to use the last 3 digits of the block ID as part of the job name to distinguish between multiple runs in the queue. In this case it will be using `.ms`. If you change the `-` in your MS name to `_` that should fix it. Here is the offending routine:

https://github.com/IanHeywood/oxkat/blob/master/oxkat/generate_jobs.py#L84

Adding a `code = code.replace('.','X')` or similar will also fix it. I'll add such a fix to the next commit.

**Comment by dentalfloss1** [comment]
Ah, gotchya! Thanks!

**Comment by IanHeywood** [comment]
Fixed here:

https://github.com/IanHeywood/oxkat/commit/ec45b7ed2796986ae704a8e87d228ca7085e958c
