### ISSUE TITLE
WSClean option logic

### ISSUE THREAD

**Issue by rdeane** [IanHeywood/oxkat#39]
Just checking the logic of these two lines:

https://github.com/IanHeywood/oxkat/blob/3c97c00567c23e1a48b08f7fb45e0a37e9fec6b9/oxkat/generate_jobs.py#L438-L439

I'm processing a narrow bandwidth dataset (so prefer ```WSC_FITSPECTRALPOL = 0```), but would like to save the source model with ```-save-source-list```. I must be missing something as to why these two parameters are coupled?

**Comment by IanHeywood** [comment]
I think it's because the spectral information is a mandatory set of columns in the source list, and wsclean won't run if a source list is requested at fit-spectral-pol is set to zero. I guess it would be fairly straightforward to turn the non-zero components in a single frequency model image into a text file, but probably not if you're using multiscale.

**Comment by rdeane** [comment]
I seem to have done that test and it does actually run, returning a source list text file with the spectral index as an empty list: 

>Format = Name, Type, Ra, Dec, I, SpectralIndex, LogarithmicSI, ReferenceFrequency='1388910156.25', MajorAxis, MinorAxis
, Orientation
>s0c0,POINT,-09:07:47.937,-10.43.29.132,3.8934647149624e-05,[],false,1388910156.25,,,

What I have not yet tested is using that file to predict into the model column - perhaps it will trip over.  

Anyway, since this is a smaller dataset, the obvious step is that should just set ```-update-model-required``` in the imaging run and avoid all of this altogether. Regardless of the outcome of the above test, I'll close "issue" (cough, user error), thanks a lot.

**Comment by IanHeywood** [comment]
There's this from the docs:

"Note that the component list therefore currently only works when using polynomial fitting in the cleaning (-fit-spectral-pol)."

But if it works I should remove that clause...

**Comment by rdeane** [comment]
Yeah, just double-checked - it definitely "works",  if one takes that to mean a _sources.txt_ file is generated, however, with the mentioned caveat that `SpectralIndex, LogarithmicSI, = [],false`, respectively.

**Comment by IanHeywood** [comment]
Fixed, cheers.
