### ISSUE TITLE
issue with slurm run and singularity settings

### ISSUE THREAD

**Issue by mauriliopannella** [IanHeywood/oxkat#47]
Hi, I cannot seem to be able to run oxkat via slurm on a local cluster. I guess this is related to Singularity settings and probably it's best if I show you directly the settings I am using:
# ------------------------------------------------------------------------
#
# Singularity settings
#

# Set to False to disable singularity entirely
USE_SINGULARITY = True

# If your data are symlinked and located in a path that singularity
# cannot see by default then set BIND to that path.
# If you wish to bind multiple paths then use a comma-separated list.
BIND = '/beegfs/clustersxcosmo/Spiderweb_MeerKAT_L/scratch/kat/1618672936_20210430T20_25_55/'
BINDPATH = '$PWD,'+CWD+','+BIND

NODE_CONTAINER_PATH = [CWD+'/containers/']
# ------------------------------------------------------------------------

and this is the submit_2GC_jobs.sh that I get:
# ------------------------------------------------------------------------
#!/usr/bin/env bash
export SINGULARITY_BINDPATH=$PWD,/beegfs/clustersxcosmo/Spiderweb_MeerKAT_L/scratch/kat/1618672936_20210430T20_25_55/oxkat,/beegfs/clustersxcosmo/Spiderweb_MeerKAT_L/scratch/kat/1618672936_20210430T20_25_55/

# Run CubiCal with f-slope solver
singularity exec /beegfs/clustersxcosmo/Spiderweb_MeerKAT_L/scratch/kat/1618672936_20210430T20_25_55/oxkat/containers/cubical_1.6.7.sif gocubical /beegfs/clustersxcosmo/Spiderweb_MeerKAT_L/scratch/kat/1618672936_20210430T20_25_55/oxkat/data/cubical/2GC_delaycal.parset --data-ms=1618672936_sdp_l0_1024ch_MRC1138-262.ms --out-dir /beegfs/clustersxcosmo/Spiderweb_MeerKAT_L/scratch/kat/1618672936_20210430T20_25_55/oxkat/GAINTABLES/delaycal_MRC1138-262_2022-02-22-12-31-33.cc/ --out-name delaycal_MRC1138-262_2022-02-22-12-31-33 --k-save-to delaycal_MRC1138-262.parmdb | tee /beegfs/clustersxcosmo/Spiderweb_MeerKAT_L/scratch/kat/1618672936_20210430T20_25_55/oxkat/LOGS/oxk_CL2GC262.log
# ------------------------------------------------------------------------

Please note that in my case PWD and CWD are the same dir and the BIND directory is where the actual physical data are, and only symlinked to CWD. When I try the following slurm run:

# ------------------------------------------------------------------------
#!/bin/bash
#SBATCH -N 1
#SBATCH -n 46
#SBATCH --mem=480000
#SBATCH -t 218:00:00
#
export SINGULARITY_BINDPATH=/beegfs/clustersxcosmo/Spiderweb_MeerKAT_L/scratch/kat/1618672936_20210430T20_25_55/oxkat,/beegfs/clustersxcosmo/Spiderweb_MeerKAT_L/scratch/kat/1618672936_20210430T20_25_55/
#---------------------------------------
# MRC1138-262
#---------------------------------------
# Run CubiCal with f-slope solver
singularity exec /beegfs/clustersxcosmo/Spiderweb_MeerKAT_L/scratch/kat/1618672936_20210430T20_25_55/oxkat/containers/cubical_1.6.7.sif gocubical /beegfs/clustersxcosmo/Spiderweb_MeerKAT_L/scratch/kat/1618672936_20210430T20_25_55/oxkat/data/cubical/2GC_delaycal.parset --data-ms=1618672936_sdp_l0_1024ch_MRC1138-262.ms --out-dir /beegfs/clustersxcosmo/Spiderweb_MeerKAT_L/scratch/kat/1618672936_20210430T20_25_55/oxkat/GAINTABLES/delaycal_MRC1138-262_2022-02-22-12-31-33.cc/ --out-name delaycal_MRC1138-262_2022-02-22-12-31-33 --k-save-to delaycal_MRC1138-262.parmdb | tee /beegfs/clustersxcosmo/Spiderweb_MeerKAT_L/scratch/kat/1618672936_20210430T20_25_55/oxkat/LOGS/oxk_CL2GC262.log
# ------------------------------------------------------------------------

It crashes with this message:

WARNING: While bind mounting '/beegfs/clustersxcosmo/Spiderweb_MeerKAT_L/scratch/kat/1618672936_20210430T20_25_55/oxkat:/beegfs/clustersxcosmo/Spiderweb_MeerKAT_L/scratch/kat/1618672936_20210430T20_25_55/oxkat':
 destination is already in the mount point list
WARNING: skipping mount of /cvmfs: stat /cvmfs: no such file or directory
FATAL:   container creation failed: mount /cvmfs->/cvmfs error: while mounting /cvmfs: mount source /cvmfs doesn't exist

Last not least, if I try to run the same commands from the terminal frontend it will just go ahead and do the job with the obvious problem now that I should not run a clean job on the cluster frontend...

Well, sorry for the waste of time and thank you in advance for any advise you might have!

Best wishes,
Maurilio

**Comment by IanHeywood** [comment]
```
WARNING: skipping mount of /cvmfs: stat /cvmfs: no such file or directory
FATAL: container creation failed: mount /cvmfs->/cvmfs error: while mounting /cvmfs: mount source /cvmfs doesn't exist
```

The above message suggests that singularity is trying to bind a path on /cvmfs. Perhaps the worker nodes cannot see this location if its runs fine from the head node, or perhaps it's something to do with the symlinks you mentioned. Sorry I can't be of any more help, I think this might be a question for the person who manages your cluster.

**Comment by mauriliopannella** [comment]
Yes, I had the same reaction to the error message. I've written to the sm here a few days ago without much luck nor a reply so far... Thanks a lot for your prompt reply. I guess you can close this issue, I'll let be in touch when/if I find out more.   Cheers.

**Comment by IanHeywood** [comment]
Please feel free to reopen if the problem is oxkat-related.
