### ISSUE TITLE
empty FLAG and 2GC.sh scripts

### ISSUE THREAD

**Issue by Kincaidr** [IanHeywood/oxkat#51]
Hi,

After running: `python3 setups/FLAG.py node` or `python3 setups/2GC.py node` the resulting .sh scripts are mostly empty and therefore nothing happens when I try to run them. This is the only content inside:

```
#!/usr/bin/env bash
export SINGULARITY_BINDPATH=$PWD,/vault-ike/kincaid/solarkat/oxkat_reduction/oxkat,
```
However, running `python3 setups/1GC.py node` does not give me this issue.

**Comment by IanHeywood** [comment]
What does the terminal output for the FLAG or 2GC say? Best guess is that 1GC has failed and it's failing to find the target Measurement Sets that the 1GC step should produce. If you can let me know how to access your working area I can take a look, otherwise a good starting point would be to just `ls -1d *.ms` in your working path and let me know what's returned.

**Comment by Kincaidr** [comment]
The terminal output says nothing. I recall the 1GC completing, I have the visibility plots which is one of the last steps.

This is what `ls -1d *.ms` returns:
```
MIGHTEE_calibrators.ms
MIGHTEE_CDFS_raw-cal_1024ch.ms
MIGHTEE_CDFS_raw-cal.ms
```
So yeah I don't see the target ms here which might be the problem. If you want you can check my working directory at: `/vault-ike/kincaid/solarkat/oxkat_reduction/oxkat`

**Comment by IanHeywood** [comment]
Thanks @Kincaidr. Any idea how to access that from nash? Maybe @o-smirnov can advise. I think there used to be more stuff in `/net`:

```
ianh@nash:~$ ls /net/
janis
```

and I can't ssh into ike directly as I don't have ssh keys set up:

```
ianh@nash:~$ ssh ianh@ike
ianh@ike: Permission denied (publickey).
```

As an aside, I'd recommend using the dev branch of oxkat.

**Comment by IanHeywood** [comment]
> The terminal output says nothing. 

If it says literally nothing then that might be a bug. It's supposed to let you know if a MS it's looking for isn't found.

**Comment by IanHeywood** [comment]
Thanks chief, got it now.

@Kincaidr the current mystery is that all the CASA logs are missing, and I fear these are the key to understanding what's happened here...

**Comment by Kincaidr** [comment]
Yes i see, my bad I linked the cal.ms instead of the raw

**Comment by IanHeywood** [comment]
No worries. Just to re-iterate my suggestion to switch to the dev branch if you are re-running it. It does away with the intermediate `calibrators.ms`, and has numerous other improvements, fixes, speed-ups.

https://github.com/IanHeywood/oxkat/compare/master...dev

Note that there's an extra 'stage 0' setup step at the beginning, although I think it's a price worth paying as you no longer have to manually specify what band the MS is. 

There is also a single container that's specific to oxkat to break the reliance on the stimela containers (although you can still use package-specific containers if you want by editing the config.py file). 

The container is here:

```
/net/nash/home/ianh/containers/oxkat-0.41.sif
```

Hope it's useful to you, cheers.
