### ISSUE TITLE
Add script to deal with NaN model images for entirely flagged sub-bands

### ISSUE THREAD

**Issue by IanHeywood** [IanHeywood/oxkat#52]
Empty (entirely flagged) sub-bands will fail on the prediction step. Need to add script to detect and fix the NaN model images that result, particularly for the peeling step with a high number of sub-bands.

See https://gitlab.com/aroffringa/wsclean/-/issues/127

**Comment by Sinenhlanhla** [comment]
Hi @IanHeywood, I am also getting this error for my prediction step. Have you been able to add the script mentioned above?

**Comment by IanHeywood** [comment]
Hi @Sinenhlanhla, no time to work on oxkat lately so don't have a direct fix, but if you pause between the imaging and the prediction you can zero the model channels that have NaNs in then with something like the following script and then resume the processing.

```
import sys
import glob
import numpy
from astropy.io import fits


def get_image(fitsfile):
    input_hdu = fits.open(fitsfile)[0]
    if len(input_hdu.data.shape) == 2:
            image = numpy.array(input_hdu.data[:,:])
    elif len(input_hdu.data.shape) == 3:
            image = numpy.array(input_hdu.data[0,:,:])
    else:
            image = numpy.array(input_hdu.data[0,0,:,:])
    return image


def flush_fits(newimage,fitsfile):
    f = fits.open(fitsfile,mode='update')
    input_hdu = f[0]
    if len(input_hdu.data.shape) == 2:
            input_hdu.data[:,:] = newimage
    elif len(input_hdu.data.shape) == 3:
            input_hdu.data[0,:,:] = newimage
    else:
            input_hdu.data[0,0,:,:] = newimage
    f.flush()


pattern = sys.argv[1]

fitslist = sorted(glob.glob('*'+pattern+'*model.fits'))

for fitsfile in fitslist:
        img = get_image(fitsfile)
        max = numpy.max(img)
        if numpy.isnan(max):
                new_img = numpy.zeros((img.shape[0],img.shape[1]))
                print(new_img.shape)
                print(fitsfile,numpy.max(img))
                flush_fits(new_img,fitsfile)
```

For a longer term solution I want to implement Lexy's smops tool to interpolate the models at this stage but again it's just time... Sorry.

**Comment by Sinenhlanhla** [comment]
@IanHeywood thank you

**Comment by IanHeywood** [comment]
Fixed.
