### ISSUE TITLE
Why keep W-corrections on in snapshot imaging?

### ISSUE THREAD

**Issue by bennahugo** [IanHeywood/oxkat#53]
https://github.com/IanHeywood/oxkat/blob/9646269fd7b221a266f53cc0ab7d8f9284c717b5/waterhole/setup_intervals.py#L95

Perusing the scripts here along the lines of saving compute cycles (I imagine this is going to become more important for the batch TK jobs). Any particular reason why you are further increasing w-corrections here @IanHeywood ?

As we are doing pure snapshot imaging the array is instantaneously coplanar already -- ie. we can get away with AIPS-style "single-facet" imaging here...  

Edit: I rate we can force w layers to 1 -- will save a ton of FFT costs (which firmly bounds us for wstacking)?

**Comment by IanHeywood** [comment]
Switched to w-gridder in line with all the other imaging in the dev branch. Thanks. 

https://github.com/IanHeywood/oxkat/commit/aec4edff3d29d520900e466fac0925434d0448b4

**Comment by bennahugo** [comment]
But this still uses w layers - it is just a different gridder. Not at my
desk now, but it would be worth setting nwlayer to 1 ( the UVW=0 plane)
because all the measurements are expected to be coplanar instantaneously
somewhere inside the uvw space which means there is a linear operator
between them and the w=0 plane. you don't need those additional fft costs
(which is where the vast majority of the runtime is spent).

The goal is essentially AIPS style snapshots with a single grid.

**Comment by IanHeywood** [comment]
Thanks Ben, I had it in my head that wsclean only had the factors option, rather than explicit control over nwlayers, so I've implemented your suggestion. The only thing to be mindful of is that when I (eventually) get around to tidying up this workflow I'd like to have an option to image arbitrary numbers of integrations for reeach frame in the movie, so the w-term might need to be considered for that use case.

**Comment by bennahugo** [comment]
Sure yes, but you can in the last case perhaps work out the expected amount of residual error in w to work out how many layers to use, instead of using Andre's calculation? Just thinking of ways to make this faster if we want to deploy this in a more automated sense for pipeline data.

I've done some stuff like that in my MSc thesis, but not for the snapshotting case (was considering w-faceting)

**Comment by IanHeywood** [comment]
Just noticed this...

```
2022-Sep-30 14:57:22.425882 The theoretically suggested number of w-layers (1) is less than the number of availables
2022-Sep-30 14:57:22.425907 cores (16). Changing suggested number of w-layers to 16.
```

😆

**Comment by bennahugo** [comment]
What a waste of processing power lol. Better to force it. Then you can have
multiple batches of stuff actually using the same machine...
