### ISSUE TITLE
typo in freq. range S3 band

### ISSUE THREAD

**Issue by saramotta** [IanHeywood/oxkat#55]
There is a very small typo in the freq. range referred to S3 in oxkat/1GC_00_setup.py. 2046MHz should be 2406MHz. 
https://github.com/IanHeywood/oxkat/blob/55ddbd0952357b5cdfc4c7ae9910a431faea6de1/oxkat/1GC_00_setup.py#L25

**Comment by IanHeywood** [comment]
Good catch. Fixed (I hope).

https://github.com/IanHeywood/oxkat/commit/4cec280b54b5a97ea372878b9abd6f416d2bb173

Cheers.
