### ISSUE TITLE
Issue running killMS

### ISSUE THREAD

**Issue by WilliamRasakanya** [IanHeywood/oxkat#64]
Hi

I have an issue when I run 3GC facet, particularly the stage where killMS is run, on ilifu.

When I run SCRIPTS/slurm_KILMS000.sh, I get the following when using container oxkat-0.42.sif :
```
/usr/local/lib/python3.9/dist-packages/killMS/Parset/DefaultParset.cfg
       __        _   __   __   ____    ____   ______
      [  |  _   (_) [  | [  | |_   \  /   _|.' ____ \
       | | / ]  __   | |  | |   |   \/   |  | (___ \_|
       | '' <  [  |  | |  | |   | |\  /| |   _.____`.
       | |`\ \  | |  | |  | |  _| |_\/_| |_ | \____) |
      [__|  \_][___][___][___]|_____||_____| \______.'
             This is version : ^[[1m^[[91mdev^[[0m^[[0m

Traceback (most recent call last):
  File "/usr/local/bin/kMS.py", line 1256, in <module>
    OP=read_options()
  File "/usr/local/bin/kMS.py", line 236, in read_options
    OP.Print(RejectGroup)
UnboundLocalError: local variable 'RejectGroup' referenced before assignment
****ELAPSED 13 KILMS000
~                             
```

When running it in container oxkat-0.41.sif (default), I get:
```
WARNING: While bind mounting '/scratch3/users/wrasakanya/Project_Infinity/p000_2_facet:/scratch3/users/wrasakanya/Project_Infinity/p000_2_facet': destination is already in the mount point list
Traceback (most recent call last):
        File "/usr/local/bin/kMS.py", line 30, in <module> 
              import killS
        File "/usr/local/lib/python3.9/dist-packages/killMS/__init___.py", line 24, in <module>
              __version__ = pkg_resources. require ("kilIMS")[0].version
       File "/us/lib/python3/dist-packages/pkg_resources/__init__.py", line 886, in require
              needed = self.resolve (parse_requirements (requirements))
       File "/us/lib/python3/dist-packages/pkg_resources/__init__.py", line 777, in resolve
               raise VersionConflict(dist, req).with_context (dependent_req)
pkg_resources.ContextualVersionConflict: (pyerfa 1.7.2 (/usr/lib/python3/dist-packages) , Requirement parse ('pyerfa>=2.0'), {'astropv' })
****ELAPSED 8 KILMS000
```

Please assist.

Before this, I would get an issue on SCRIPTS/slurm_RG2NP000.sh (Convert the DS9 region into a numpy file that killMS will recognise), where regions could not be converted because setups/reg2npy.py assumed that the DS9 regions were only in HMS,DMS format. I modified this file so it wouldn't try to convert my coordinates to deg, as they already were. And subsequently, the npy files were created without an issue. My DS9 regions were created in CARTA. I suggest having some _if statement_ to consider the different coordinate formats.

**Comment by IanHeywood** [comment]
Hello.

killMS has never worked in the 0.42 container, due to some dependency conflicts, but everything that oxkat does by default should work with the 0.41 container (I've run this step successfully on IDIA very recently). So I don't know what's going on here, sorry. Have you modified anything, or tried to install killMS locally in a venv or anything?

The `killS`, `ki11MS`, `kilIMS` etc. in the log is weird. 

Regarding the regions problem: This is actually CARTA not writing out DS9 region files in the same format that DS9 does. I should make the script CARTA compatible but I've never gotten around to it as I've always just used DS9 to define the regions. Feel free to issue a pull request.

Cheers.

**Comment by WilliamRasakanya** [comment]
Thanks for the speedy response.

I had issues running Cubical in the 2GC stage (SCRIPTS/slurm_CL2GC000.sh) using the 0.41 container, so I had that changed to 0.42, which then worked. 0.41 gave me an error for Cubical.
This is the only change I had.
I have not tried to install killMS at all. I have shadeMS in a venv, but I doubt that's the issue. 

Oh okay, I see. Will do.

Thanks

**Comment by IanHeywood** [comment]
Weird... Sorry it's causing you problems.

Can you give me access to your path / MS so I can try processing it please?

**Comment by WilliamRasakanya** [comment]
The `killS`, `ki11MS`, `kilIMS` seems to be my error during copying (I copied the error from an image I had a screenshot of). I double-checked the error and it just says `killMS`.

The original MS is in 
> /idia/data/pretoria/RATTbusyweek/scratch/kat/1681552950_20230804T13_05_26/

I gave you permissions to directory:
>/scratch3/users/wrasakanya/Project_Infinity/p000_2_facet/
I hope I did that right. LEt me know if I didn't.

**Comment by IanHeywood** [comment]
For the /scratch3 path, I think you have to give me permission all the way to the username directory for me to see the subdirectory, which I understand if you do not want to do.

I can see the /idia/data/pretoria path though, I've started a processing run on that MS and will let you know if I get the same errors.

**Comment by WilliamRasakanya** [comment]
What command should I use to give you access? Can you give me an example?
I'm not that good yet at this stuff 😅

**Comment by IanHeywood** [comment]
You and me both...!

Maybe:

```
$ chmod -R a+rx /scratch3/users/wrasakanya/
```

I think this will recursively grant read and execute access to every location below that one, although this will grant this access for _everyone_. So make sure you're okay with that.

Alternatively we can see if the separate processing I'm doing fails.

**Comment by WilliamRasakanya** [comment]
In that case, I think I'll refrain from doing that as some data may be sensitive.
I just had a meeting with my supervisor, and he suspects the problem may be occurring before the killMS stage, So I'll also do a separate processing and see if the error occurs upstream.

**Comment by IanHeywood** [comment]
Can't see how an upstream processing error could break the container, but let's keep digging.

**Comment by WilliamRasakanya** [comment]
Regarding the regions issue above, in which you suggested I issue a pull request - I could not issue one as GitHub gave me this error: Pull request creation failed. Validation failed: must be a collaborator.
So instead, I'll put it here:


The tools/reg2npy.py script assumes that the DS9 regions file has coordinates in the format of HMS,DMS,rad and separated by colons.
DS9 format regions not created in SAOImageDS9 (such as those created using CARTA) are already in degree units: deg, deg, rad.

I recommend making the following changes in lines 65 and 66:
```
            ra = hms2deg(x)
            dec = dms2deg(y)
```

to

```
            if ':' in x == True or ':' in y == True:
                ra = hms2deg(x)
                dec = dms2deg(y)
                
            elif ('h' and 'm' and 's') in x or (':') in x == False:
                ra = float(x) 
                dec = float(y) 
```

This way, if the coordinates are already in units of degrees, then no conversion is necessary.

**Comment by IanHeywood** [comment]
I can confirm I get the same error as you do for 0.42, but with the default 0.41 container:

```
       __        _   __   __   ____    ____   ______
      [  |  _   (_) [  | [  | |_   \  /   _|.' ____ \
       | | / ]  __   | |  | |   |   \/   |  | (___ \_|
       | '' <  [  |  | |  | |   | |\  /| |   _.____`.
       | |`\ \  | |  | |  | |  _| |_\/_| |_ | \____) |
      [__|  \_][___][___][___]|_____||_____| \______.'
             This is version : 3.0.1.0

Traceback (most recent call last):
  File "/usr/local/bin/kMS.py", line 1256, in <module>
    OP=read_options()
  File "/usr/local/bin/kMS.py", line 236, in read_options
    OP.Print(RejectGroup)
UnboundLocalError: local variable 'RejectGroup' referenced before assignment
****ELAPSED 1 KILMS2_4
```

and not just for your data either.

I have no idea what's going on at the moment.

**Comment by IanHeywood** [comment]
Re: your data, all three pointing ran just fine to the post-2GC stage. The DI-selfcal made significant improvements, but I agree some direction dependent treatment is necessary.

**Comment by IanHeywood** [comment]
OK, looking at the killMS code makes me spot the oxkat bug. Please pull the current master and it will hopefully be fixed, let me know if it's still problematic. 

I'll keep this open as a reminder to fix the DS9 / CARTA region thing too.

Thanks for reporting this and sorry for the hassle.

**Comment by IanHeywood** [comment]
Seems to be producing sensible results again, and I've added the fix to allow CARTA region files for the 3GC facet stage. Please reopen if you encounter problems.

**Comment by WilliamRasakanya** [comment]
Hi Ian

Thanks for all the help. I shall do as advised.
Much appreciated!
